// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF_buvhIUmf6J1-q-CS7oEewE6agAVyr0',
    appId: '1:515416426951:android:71359eb0860f6729c8b1e2',
    messagingSenderId: '515416426951',
    projectId: 'zen-app-32585',
    storageBucket: 'zen-app-32585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZP6N2zQLOnYkVtH5UKE9Mcg1sruoOlOs',
    appId: '1:515416426951:ios:81e84dea71d6d377c8b1e2',
    messagingSenderId: '515416426951',
    projectId: 'zen-app-32585',
    storageBucket: 'zen-app-32585.firebasestorage.app',
    iosBundleId: 'com.example.zenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-LOrnCoOmSB3nJjpBqn0Pi1UrPxNY1_g',
    appId: '1:515416426951:web:c0f8be67740e4c13c8b1e2',
    messagingSenderId: '515416426951',
    projectId: 'zen-app-32585',
    authDomain: 'zen-app-32585.firebaseapp.com',
    storageBucket: 'zen-app-32585.firebasestorage.app',
  );
}
